---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  InstanceType:
    Type: String
    Default: "m4.xlarge"
  ReleaseLabel:
    Type: String
    Default: "emr-6.5.0"
  SubnetId:
    Type: String
    Default: "subnet-66d1882a"
  MinimumCapacityUnits:
    Type: String
    Default: "3"
  MaximumCapacityUnits:
    Type: String
    Default: "10"
  MaximumCoreCapacityUnits:
    Type: String
    Default: "2"
  MaximumOnDemandCapacityUnits:
    Type: String
    Default: "8"
  UnitType:
    Type: String
    Default: "Instances"
Resources:
  cluster:
    Type: AWS::EMR::Cluster
    Properties:
      Instances:
        MasterInstanceGroup:
          InstanceCount: 1
          InstanceType:
            Ref: InstanceType
          Market: ON_DEMAND
          Name: primary
        CoreInstanceGroup:
          InstanceCount: 1
          InstanceType:
            Ref: InstanceType
          Market: ON_DEMAND
          Name: core
        TaskInstanceGroups:
        - InstanceCount: 1
          InstanceType:
            Ref: InstanceType
          Market: ON_DEMAND
          Name: cfnTask-1
        - InstanceCount: 1
          InstanceType:
            Ref: InstanceType
          Market: ON_DEMAND
          Name: cfnTask-2
        Ec2SubnetId:
          Ref: SubnetId
      Name: ManagedScalingExample
      JobFlowRole: EMR_EC2_DefaultRole
      ServiceRole: EMR_DefaultRole
      ReleaseLabel:
        Ref: ReleaseLabel
      ManagedScalingPolicy:
        ComputeLimits:
          MinimumCapacityUnits:
            Ref: MinimumCapacityUnits
          MaximumCapacityUnits:
            Ref: MaximumCapacityUnits
          MaximumCoreCapacityUnits:
            Ref: MaximumCoreCapacityUnits
          MaximumOnDemandCapacityUnits:
            Ref: MaximumOnDemandCapacityUnits
          UnitType:
            Ref: UnitType
